# Generated by Django 4.1.1 on 2023-08-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateTimeField()),
                ('createur', models.TextField()),
                ('source', models.TextField()),
                ('responsable', models.TextField()),
                ('nature', models.TextField()),
                ('tache', models.TextField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/user.jpg', upload_to='users/')),
                ('biography', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('studies', models.CharField(default='Unknown', max_length=100)),
                ('phone', models.CharField(default='000-000-0000', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
