# Generated by Django 4.1.1 on 2023-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planTaskk', '0002_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studies',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
