# Generated by Django 4.1.2 on 2023-09-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planTaskk', '0003_alter_userprofile_biography_and_more'),
        ('planTaskk', '0003_todo_commentaire_alter_userprofile_biography_and_more'),
    ]

    operations = [
    ]
