# Generated by Django 4.1.2 on 2023-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planTaskk', '0004_merge_20230906_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='interne',
            field=models.TextField(default='Foued'),
            preserve_default=False,
        ),
    ]
