# Generated by Django 4.1.2 on 2023-09-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planTaskk', '0005_todo_interne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='interne',
            field=models.TextField(blank=True),
        ),
    ]
